baseURL = 'https://iilei.github.io/'
languageCode = 'en-us'
title = 'iilei â€¢ jochen preusche'

# Add custom params here
[params]
description = "iilei - jochen preusche's personal website"
author = "Jochen Preusche"
# Add any custom variables you want to use in templates
customCSS = ["css/custom.css"]